20260211
recording some nlp tricks

use anchor in sentence similarity comparison

In [1]:
# don't know, should always use: ./.venv//bin/python -m pip install sentence_transformers

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
 
# Initialize model and encode anchors
model = SentenceTransformer('all-MiniLM-L6-v2')
anchors = ["billing issue", "login problem", "feature request"]
anchor_embeddings = model.encode(anchors)
 
# Encode a new ticket
new_ticket = ["I can't access my account, it says password invalid."]
ticket_embedding = model.encode(new_ticket)
 
# Calculate similarity features
similarity_features = cosine_similarity(ticket_embedding, anchor_embeddings)
print(similarity_features)  # e.g., [[0.1, 0.85, 0.3]] -> high similarity to "login problem"

/Users/lilun.zhang/VSCodeProjects/aie/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1104.34it/s, Materializing param=pooler.dense.weight]                             
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[[0.36162615 0.5896069  0.03221758]]


try business case（used for text classification)

In [ ]:
# don't know, should always use: ./.venv//bin/python -m pip install sentence_transformers

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
 
# Initialize model and encode anchors
model = SentenceTransformer('shibing624/text2vec-base-chinese')
anchors = ["买车", "没提到要买车"]
anchor_embeddings = model.encode(anchors)
 
# Encode a new ticket
new_ticket = ["ET9展车已到门店，从兰州新区接送用户到万象城门店看车，单程60公里"]
ticket_embedding = model.encode(new_ticket)
 
# Calculate similarity features
similarity_features = cosine_similarity(ticket_embedding, anchor_embeddings)
print(similarity_features)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 975.10it/s, Materializing param=pooler.dense.weight]                               
BertModel LOAD REPORT from: shibing624/text2vec-base-chinese
Key                          | Status     |  | 
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[[0.36438686 0.42217815]]


In [ ]:
# 测试：能否提取几种汽车品牌，不准。觉得是too specific。比如上面这种general带语义的判断结果还ok。

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
 
# Initialize model and encode anchors
model = SentenceTransformer('shibing624/text2vec-base-chinese')
anchors = ["提到多个汽车品牌", "仅提到一种汽车品牌", "未提到汽车品牌"]
anchor_embeddings = model.encode(anchors)
 
# Encode a new ticket
new_ticket = ["用户是经常在国外，但是一直有在炒股，比较关注蔚来，每次有新车型上市都会关心讨论。用户也接触过好几个顾问，但是觉得回复速度和专业性会差一些，比较认可我们。下单前，用户提出想要有人能接一下，跟淳淳约了et9体验，帮他协调，可以去接送他，觉得很尊贵，后面满意锁单"]
ticket_embedding = model.encode(new_ticket)
 
# Calculate similarity features
similarity_features = cosine_similarity(ticket_embedding, anchor_embeddings)
print(similarity_features)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1021.08it/s, Materializing param=pooler.dense.weight]                              
BertModel LOAD REPORT from: shibing624/text2vec-base-chinese
Key                          | Status     |  | 
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[[0.5112165  0.5099434  0.42966738]]
